apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: http
    nodePort: 32222
  selector:
    app: nginx
  type: NodePort
